.********************************************************
:userdoc.
:docprof toc=123.
:title.Musik-Memory
.******************************************
:h1 res=100.  Regeln
:p.
Dieses kleine Programm ist eine Art Memory mit Noten.
:p.
W„hlen Sie "Neues Spiel" aus dem Men, um eine neue Serie zu beginnen.
Nach einem Mausklick wird Ihnen der PC die ersten beiden Noten vorspielen.
Spielen Sie die T”ne nach, indem Sie auf die Farbfl„chen klicken.
:p.
Nach einem erneuten Klick wird die Melodie um einen Ton l„nger. Spielen Sie
die Melodie nach und klicken Sie erneut, um jeweils einen Ton mehr zu h”ren
und zu sehen.
:p.
Das Programm sollte Ihnen mit Source vorliegen. Wenn nicht, schreiben Sie 
an
:xmp.
    Dr. R. Grothmann
    Kath. Univ. Eichst„tt
    85072 Eichst„tt
    Germany

    EMail: rene.grothmann@ku-eichstaett.de
:exmp.:p.
:euserdoc.
